name: Mutation testing
on:
  push:
    branches:
      - main

jobs:
  mutation_testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: 📦 Install dependencies
        run: npm ci --engine-strict
      - name: 👽 Mutation testing
        run: npm run test:mutation
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
